eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-cheerful-fox.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePortEnabled: false
    securePortEnabled: true

spring:
  rabbitmq:
    host: spider-01.rmq.cloudamqp.com
    virtual-host: nhsbsmng
    username: nhsbsmng
    password: hJq4gSoszGqS1O1Vdl8ygtdNY5s6g8WF
  cloud:
    stream:
      bindings:
        input:
          destination: ping-pong
  jpa:
    hibernate:
      ddl-auto: none
      dialect: mysql
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/ad_e30a71cf6f98faa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: b0ebc640488958
    password: 7f038be0
    max-active: 2
